[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/flutterwave/*"
  to = "/.netlify/functions/flutterwave-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhooks/flutterwave"
  to = "/.netlify/functions/webhooks-flutterwave.cjs"
  status = 200
  force = true 