[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/flutterwave/*"
  to = "/.netlify/functions/flutterwave-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhooks/flutterwave"
  to = "/.netlify/functions/webhooks-flutterwave"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 